@apiurl = http://127.0.0.1:3333/api

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1NGI3YThhNC00YTc5LTQ1N2UtYjhmMC0yMGRhZDE5ZmUwNDgiLCJpYXQiOjE3MTcwOTQ3MTEsImV4cCI6MTcyMjI3ODcxMX0.6jmPXDkjUF3ADvwYJ19c_A2oBVD9UF8rRKPYOKPNTSQ

@entityId=107f00b2-997f-4707-b7e0-772104d5a863

@routeId=0184be9b-5a03-4740-9080-b7be7c5f4265

@entityType=routeDriver

### POST add
POST {{apiurl}}/{{entityType}}/add  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Route Driver 3",
  "routeId": "0184be9b-5a03-4740-9080-b7be7c5f4265",
  "points": [
  ],
  "status": "INICIADO",
  "active": true,
  "createdAt": "2024-05-31T14:53:00Z",
  "updatedAt": "2024-05-31T14:53:00Z"
}


### GET loadById
GET {{apiurl}}/{{entityType}}/load?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET loadByPage
GET {{apiurl}}/{{entityType}}/loadByPage?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### PATCH update
PATCH {{apiurl}}/{{entityType}}/update?_id={{entityId}}&routeId={{routeId}}&lat=33&lng=33 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "FINALIZADO"
}

### DELETE delete
DELETE {{apiurl}}/{{entityType}}/delete?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

