CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
    "_id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "createdById" UUID,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "role" VARCHAR(255) NOT NULL,
    "confirmedEmail" BOOLEAN DEFAULT FALSE,
    "sendedEmail" BOOLEAN DEFAULT FALSE,
    "password" VARCHAR(255) NOT NULL,
    "cardId" UUID,
    "ownerId" UUID,
    "myOwnerId" UUID,
    "payDay" VARCHAR(255),
    "photoUrl" VARCHAR(255),
    "cpf" VARCHAR(255),
    "phone" VARCHAR(255),
    "coord" JSONB,
    "distance" NUMERIC,
    "appointmentsTotal" INT DEFAULT 0,
    "plan" VARCHAR(255),
    "cnpj" VARCHAR(255),
    "city" VARCHAR(255),
    "uf" VARCHAR(255),
    "address" TEXT,
    "complement" TEXT,
    "photoId" UUID,
    "cash" BOOLEAN DEFAULT FALSE,
    "creditcard" BOOLEAN DEFAULT FALSE,
    "debitcard" BOOLEAN DEFAULT FALSE,
    "transferbank" BOOLEAN DEFAULT FALSE,
    "cheque" BOOLEAN DEFAULT FALSE,
    "pix" BOOLEAN DEFAULT FALSE,
    "nextPlan" VARCHAR(255),
    "addresses" JSONB,
    "clientId" UUID,
    "active" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "serviceIds" VARCHAR(255)[],
    "serviceOptions" JSONB[],
    "globalID" UUID,
    FOREIGN KEY ("createdById") REFERENCES users("_id"),
    FOREIGN KEY ("myOwnerId") REFERENCES users("_id")
);
