export const NEW_STATUS_ARRAY_THAT_NEEDS_APPOINTMENT_IN_FUTURE = [1, 2, 3, 5, 6, 7, 8];
export const NEW_STATUS_ARRAY_THAT_NEEDS_APPOINTMENT_IN_PAST = [9, 10, 11];

export const ACCEPTABLE_DIFFERENCE_IN_MINUTES_TO_RATE = 5000;
export const ACCEPTABLE_DIFFERENCE_IN_MINUTES_TO_CANCEL = -60;
export const ACCEPTABLE_DIFFERENCE_IN_MINUTES_TO_RESCHEDULE = -50;

export const CANCELLED_STATUS_ARRAY = [2, 3];
export const RESCHEDULE_STATUS_ARRAY = [5, 6];
export const RATED_STATUS_ARRAY = [11, 9];
