@apiurl = http://127.0.0.1:3333/api

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxMjVlNTAxYi1hZTU5LTQ1ZDctOGI0Zi1iMjJmZjU0M2EwNjUiLCJpYXQiOjE3MjkxNjgwMzAsImV4cCI6MTczNDM1MjAzMH0.nrskBqeuAj6J3MDDHUxqYunIbtWaYjmJ1AXEAPLOFsg




@entityId=99c818aa-c2ec-44ee-b6be-c68b99b3566e

@entityType=tweetlike

@tweetId=2d911a20-305b-4c00-b14d-b3be3ec5f8f0

### POST add
POST {{apiurl}}/{{entityType}}/toggleLike  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userSlug": "devdoido2",
  "tweetId": "2d911a20-305b-4c00-b14d-b3be3ec5f8f0"
}

### GET loadById
GET {{apiurl}}/{{entityType}}/load?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET loadByPage
GET {{apiurl}}/{{entityType}}/loadByPage?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### PATCH update
PATCH {{apiurl}}/{{entityType}}/update?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userSlug": "devlouco"
}

### DELETE delete
DELETE {{apiurl}}/{{entityType}}/delete?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

