@apiurl = http://127.0.0.1:3333/api

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxMGUzZWVlMi01NWM4LTRlYTYtODcyNi0wOTI1NmJjMmUwN2QiLCJpYXQiOjE3MzkyNzY2OTEsImV4cCI6MTc0NDQ2MDY5MX0.JVXpijpdMvhiZq0NyQg33OhXWK-nsBzElYwInOuPnFU





@entityId=c294ef34-a063-4efb-863b-2821ebe55482

@entityType=tweetlike

@tweetId=8dcb0fce-3f69-4077-ad70-4e374a5538c1

### POST add
POST {{apiurl}}/{{entityType}}/toggleLike  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userSlug": "devdoido2",
  "tweetId": "8dcb0fce-3f69-4077-ad70-4e374a5538c1"
}

### GET loadById
GET {{apiurl}}/{{entityType}}/load?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET loadByPage
GET {{apiurl}}/{{entityType}}/loadByPage?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### PATCH update
PATCH {{apiurl}}/{{entityType}}/update?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userSlug": "devlouco"
}

### DELETE delete
DELETE {{apiurl}}/{{entityType}}/delete?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

