### Variables
@apiurl = http://127.0.0.1:3333/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI3MmI1OWNiYS1mOTk3LTRkMGItODcxYy0zNmZhZGZkNzkwZTIiLCJpYXQiOjE3MTY1NzM2NjQsImV4cCI6MTcyMTc1NzY2NH0.pBAY6QhssN_KUd0qFFKh8h-GbHpS0ZJZ2vUCUokJt60
@entity=owner
@entityId=9b444370-6851-47bc-8235-952f8dfc19bc



### POST add entity
POST {{apiurl}}/{{entity}}/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Owner do devdoido",
  "description": "Owner do devdoido",
  "haveDelivery": false,
  "minimumTimeForReSchedule": 40,
  "days1": {
  "monday1": true,
  "sunday1": true,
  "thursday1": true,
  "wednesday1": true,
  "tuesday1": true,
  "friday1": true,
  "saturday1": true
  },
  "hourStart1": "8:00",
  "hourEnd1": "18:00"
}

### PATCH update entity
PATCH {{apiurl}}/{{entity}}/update?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "teste 123s"
}

### DELETE delete entity
DELETE {{apiurl}}/{{entity}}/delete?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET loadEntityById entity
GET {{apiurl}}/{{entity}}/load?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### GET loadEntityByPage entity
GET {{apiurl}}/{{entity}}/loadByPage?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
