import { idSchema } from "@/application/types/id";
export const ownerFields = {
  description: { type: "string" },
  haveDelivery: { type: "boolean", nullable: true },
  minimumTimeForReSchedule: { type: "integer" },
  days1: {
    type: "object",
    required: [
      "monday1",
      "sunday1",
      "thursday1",
      "wednesday1",
      "tuesday1",
      "friday1",
      "saturday1",
    ],
    properties: {
      monday1: { type: "boolean" },
      sunday1: { type: "boolean" },
      thursday1: { type: "boolean" },
      wednesday1: { type: "boolean" },
      tuesday1: { type: "boolean" },
      friday1: { type: "boolean" },
      saturday1: { type: "boolean" },
    },
  },
  hourStart1: { type: "string" },
  hourEnd1: { type: "string" },
  days2: {
    type: "object",
    nullable: true,
    required: [
      "monday2",
      "sunday2",
      "thursday2",
      "wednesday2",
      "tuesday2",
      "friday2",
      "saturday2",
    ],
    properties: {
      monday2: { type: "boolean", nullable: true },
      sunday2: { type: "boolean", nullable: true },
      thursday2: { type: "boolean", nullable: true },
      wednesday2: { type: "boolean", nullable: true },
      tuesday2: { type: "boolean", nullable: true },
      friday2: { type: "boolean", nullable: true },
      saturday2: { type: "boolean", nullable: true },
    },
  },
  hourStart2: { type: "string", nullable: true },
  hourEnd2: { type: "string", nullable: true },
  days3: {
    type: "object",
    nullable: true,
    required: [
      "monday3",
      "sunday3",
      "thursday3",
      "wednesday3",
      "tuesday3",
      "friday3",
      "saturday3",
    ],
    properties: {
      monday3: { type: "boolean", nullable: true },
      sunday3: { type: "boolean", nullable: true },
      thursday3: { type: "boolean", nullable: true },
      wednesday3: { type: "boolean", nullable: true },
      tuesday3: { type: "boolean", nullable: true },
      friday3: { type: "boolean", nullable: true },
      saturday3: { type: "boolean", nullable: true },
    },
  },
  hourStart3: { type: "string", nullable: true },
  hourEnd3: { type: "string", nullable: true },
  hourLunchStart1: { type: "string", nullable: true },
  hourLunchEnd1: { type: "string", nullable: true },
  hourLunchStart2: { type: "string", nullable: true },
  hourLunchEnd2: { type: "string", nullable: true },
  hourLunchStart3: { type: "string", nullable: true },
  hourLunchEnd3: { type: "string", nullable: true },
};
const bodyAddOwnerJsonSchema = {
  type: "object",
  required: [
    "description",
    "hourStart1",
    "hourEnd1",
    "days1",
    "haveDelivery",
    "minimumTimeForReSchedule",
    "name",
  ],
  properties: {
    name: { type: "string" },
    description: { type: "string" },
    haveDelivery: { type: "boolean" },
    minimumTimeForReSchedule: { type: "integer" },
    days1: {
      type: "object",
      required: [
        "monday1",
        "sunday1",
        "thursday1",
        "wednesday1",
        "tuesday1",
        "friday1",
        "saturday1",
      ],
      properties: {
        monday1: { type: "boolean" },
        sunday1: { type: "boolean" },
        thursday1: { type: "boolean" },
        wednesday1: { type: "boolean" },
        tuesday1: { type: "boolean" },
        friday1: { type: "boolean" },
        saturday1: { type: "boolean" },
      },
    },
    hourStart1: { type: "string" },
    hourEnd1: { type: "string" },
    days2: {
      type: "object",
      required: [
        "monday2",
        "sunday2",
        "thursday2",
        "wednesday2",
        "tuesday2",
        "friday2",
        "saturday2",
      ],
      properties: {
        monday2: { type: "boolean" },
        sunday2: { type: "boolean" },
        thursday2: { type: "boolean" },
        wednesday2: { type: "boolean" },
        tuesday2: { type: "boolean" },
        friday2: { type: "boolean" },
        saturday2: { type: "boolean" },
      },
    },
    hourStart2: { type: "string" },
    hourEnd2: { type: "string" },
    days3: {
      type: "object",
      required: [
        "monday3",
        "sunday3",
        "thursday3",
        "wednesday3",
        "tuesday3",
        "friday3",
        "saturday3",
      ],
      properties: {
        monday3: { type: "boolean" },
        sunday3: { type: "boolean" },
        thursday3: { type: "boolean" },
        wednesday3: { type: "boolean" },
        tuesday3: { type: "boolean" },
        friday3: { type: "boolean" },
        saturday3: { type: "boolean" },
      },
    },
    hourStart3: { type: "string" },
    hourEnd3: { type: "string" },
    hourLunchStart1: { type: "string" },
    hourLunchEnd1: { type: "string" },
    hourLunchStart2: { type: "string" },
    hourLunchEnd2: { type: "string" },
    hourLunchStart3: { type: "string" },
    hourLunchEnd3: { type: "string" },
  },
};
const headersJsonSchema = {
  type: "object",
  properties: {
    authorization: { type: "string" },
  },
  required: ["authorization"],
};
const addOwnerResponse = {
  type: "object",
  properties: {
    _id: idSchema,
    name: { type: "string" },
    ...ownerFields,
    active: { type: "boolean", nullable: true },
    createdById: { type: "string" },
    createdAt: { type: "string" },
  },
};
export const addOwnerPostSchema = {
  schema: {
    body: bodyAddOwnerJsonSchema,
    response: { 200: addOwnerResponse },
    headers: headersJsonSchema,
    security: [{ bearerAuth: [] }],
  },
};

const queryStringJsonLoadOwnerSchema = {
  type: "object",
  properties: {},
  required: [],
};
const loadOwnerResponse = {
  type: "object",
  properties: {
    _id: idSchema,
    name: { type: "string" },
    description: { type: "string" },
    haveDelivery: { type: "boolean", nullable: true },
    minimumTimeForReSchedule: { type: "integer" },
    days1: {
      type: "object",
      required: [
        "monday1",
        "sunday1",
        "thursday1",
        "wednesday1",
        "tuesday1",
        "friday1",
        "saturday1",
      ],
      properties: {
        monday1: { type: "boolean" },
        sunday1: { type: "boolean" },
        thursday1: { type: "boolean" },
        wednesday1: { type: "boolean" },
        tuesday1: { type: "boolean" },
        friday1: { type: "boolean" },
        saturday1: { type: "boolean" },
      },
    },
    hourStart1: { type: "string" },
    hourEnd1: { type: "string" },
    days2: {
      type: "object",
      nullable: true,
      required: [
        "monday2",
        "sunday2",
        "thursday2",
        "wednesday2",
        "tuesday2",
        "friday2",
        "saturday2",
      ],
      properties: {
        monday2: { type: "boolean", nullable: true },
        sunday2: { type: "boolean", nullable: true },
        thursday2: { type: "boolean", nullable: true },
        wednesday2: { type: "boolean", nullable: true },
        tuesday2: { type: "boolean", nullable: true },
        friday2: { type: "boolean", nullable: true },
        saturday2: { type: "boolean", nullable: true },
      },
    },
    hourStart2: { type: "string", nullable: true },
    hourEnd2: { type: "string", nullable: true },
    days3: {
      type: "object",
      nullable: true,
      required: [
        "monday3",
        "sunday3",
        "thursday3",
        "wednesday3",
        "tuesday3",
        "friday3",
        "saturday3",
      ],
      properties: {
        monday3: { type: "boolean", nullable: true },
        sunday3: { type: "boolean", nullable: true },
        thursday3: { type: "boolean", nullable: true },
        wednesday3: { type: "boolean", nullable: true },
        tuesday3: { type: "boolean", nullable: true },
        friday3: { type: "boolean", nullable: true },
        saturday3: { type: "boolean", nullable: true },
      },
    },
    hourStart3: { type: "string", nullable: true },
    hourEnd3: { type: "string", nullable: true },
    hourLunchStart1: { type: "string", nullable: true },
    hourLunchEnd1: { type: "string", nullable: true },
    hourLunchStart2: { type: "string", nullable: true },
    hourLunchEnd2: { type: "string", nullable: true },
    hourLunchStart3: { type: "string", nullable: true },
    hourLunchEnd3: { type: "string", nullable: true },
    active: { type: "boolean", nullable: true },
    createdById: { type: "string" },
    createdAt: { type: "string" },
  },
};
export const loadOwnerGetSchema = {
  schema: {
    headers: headersJsonSchema,
    security: [{ bearerAuth: [] }],
    querystring: queryStringJsonLoadOwnerSchema,
    response: {
      200: loadOwnerResponse,
    },
  },
};
const deleteOwnerResponse = { type: "boolean" };
const queryStringJsonDeleteOwnerSchema = {
  type: "object",
  properties: {
    _id: idSchema,
  },
  required: ["_id"],
};
export const deleteOwnerSchema = {
  schema: {
    headers: headersJsonSchema,
    security: [{ bearerAuth: [] }],
    querystring: queryStringJsonDeleteOwnerSchema,
    response: {
      200: deleteOwnerResponse,
    },
  },
};
const queryStringJsonUpdateOwnerSchema = {
  type: "object",
  properties: {
    _id: idSchema,
  },
  required: ["_id"],
};
const updateOwnerResponse = {
  type: "object",
  properties: {
    _id: idSchema,
    name: { type: "string" },
    description: { type: "string" },
    haveDelivery: { type: "boolean", nullable: true },
    minimumTimeForReSchedule: { type: "integer" },
    days1: {
      type: "object",
      required: [
        "monday1",
        "sunday1",
        "thursday1",
        "wednesday1",
        "tuesday1",
        "friday1",
        "saturday1",
      ],
      properties: {
        monday1: { type: "boolean" },
        sunday1: { type: "boolean" },
        thursday1: { type: "boolean" },
        wednesday1: { type: "boolean" },
        tuesday1: { type: "boolean" },
        friday1: { type: "boolean" },
        saturday1: { type: "boolean" },
      },
    },
    hourStart1: { type: "string" },
    hourEnd1: { type: "string" },
    days2: {
      type: "object",
      nullable: true,
      required: [
        "monday2",
        "sunday2",
        "thursday2",
        "wednesday2",
        "tuesday2",
        "friday2",
        "saturday2",
      ],
      properties: {
        monday2: { type: "boolean", nullable: true },
        sunday2: { type: "boolean", nullable: true },
        thursday2: { type: "boolean", nullable: true },
        wednesday2: { type: "boolean", nullable: true },
        tuesday2: { type: "boolean", nullable: true },
        friday2: { type: "boolean", nullable: true },
        saturday2: { type: "boolean", nullable: true },
      },
    },
    hourStart2: { type: "string", nullable: true },
    hourEnd2: { type: "string", nullable: true },
    days3: {
      type: "object",
      nullable: true,
      required: [
        "monday3",
        "sunday3",
        "thursday3",
        "wednesday3",
        "tuesday3",
        "friday3",
        "saturday3",
      ],
      properties: {
        monday3: { type: "boolean", nullable: true },
        sunday3: { type: "boolean", nullable: true },
        thursday3: { type: "boolean", nullable: true },
        wednesday3: { type: "boolean", nullable: true },
        tuesday3: { type: "boolean", nullable: true },
        friday3: { type: "boolean", nullable: true },
        saturday3: { type: "boolean", nullable: true },
      },
    },
    hourStart3: { type: "string", nullable: true },
    hourEnd3: { type: "string", nullable: true },
    hourLunchStart1: { type: "string", nullable: true },
    hourLunchEnd1: { type: "string", nullable: true },
    hourLunchStart2: { type: "string", nullable: true },
    hourLunchEnd2: { type: "string", nullable: true },
    hourLunchStart3: { type: "string", nullable: true },
    hourLunchEnd3: { type: "string", nullable: true },
    active: { type: "boolean", nullable: true },
    createdById: { type: "string" },
    createdAt: { type: "string" },
  },
};
const updateOwnerBody = {
  type: "object",
  properties: {
    name: { type: "string" },
    description: { type: "string" },
    haveDelivery: { type: "boolean", nullable: true },
    minimumTimeForReSchedule: { type: "integer" },
    days1: {
      type: "object",
      required: [
        "monday1",
        "sunday1",
        "thursday1",
        "wednesday1",
        "tuesday1",
        "friday1",
        "saturday1",
      ],
      properties: {
        monday1: { type: "boolean" },
        sunday1: { type: "boolean" },
        thursday1: { type: "boolean" },
        wednesday1: { type: "boolean" },
        tuesday1: { type: "boolean" },
        friday1: { type: "boolean" },
        saturday1: { type: "boolean" },
      },
    },
    hourStart1: { type: "string" },
    hourEnd1: { type: "string" },
    days2: {
      type: "object",
      nullable: true,
      required: [
        "monday2",
        "sunday2",
        "thursday2",
        "wednesday2",
        "tuesday2",
        "friday2",
        "saturday2",
      ],
      properties: {
        monday2: { type: "boolean", nullable: true },
        sunday2: { type: "boolean", nullable: true },
        thursday2: { type: "boolean", nullable: true },
        wednesday2: { type: "boolean", nullable: true },
        tuesday2: { type: "boolean", nullable: true },
        friday2: { type: "boolean", nullable: true },
        saturday2: { type: "boolean", nullable: true },
      },
    },
    hourStart2: { type: "string", nullable: true },
    hourEnd2: { type: "string", nullable: true },
    days3: {
      type: "object",
      nullable: true,
      required: [
        "monday3",
        "sunday3",
        "thursday3",
        "wednesday3",
        "tuesday3",
        "friday3",
        "saturday3",
      ],
      properties: {
        monday3: { type: "boolean", nullable: true },
        sunday3: { type: "boolean", nullable: true },
        thursday3: { type: "boolean", nullable: true },
        wednesday3: { type: "boolean", nullable: true },
        tuesday3: { type: "boolean", nullable: true },
        friday3: { type: "boolean", nullable: true },
        saturday3: { type: "boolean", nullable: true },
      },
    },
    hourStart3: { type: "string", nullable: true },
    hourEnd3: { type: "string", nullable: true },
    hourLunchStart1: { type: "string", nullable: true },
    hourLunchEnd1: { type: "string", nullable: true },
    hourLunchStart2: { type: "string", nullable: true },
    hourLunchEnd2: { type: "string", nullable: true },
    hourLunchStart3: { type: "string", nullable: true },
    hourLunchEnd3: { type: "string", nullable: true },
  },
};
export const updateOwnerSchema = {
  schema: {
    headers: headersJsonSchema,
    security: [{ bearerAuth: [] }],
    querystring: queryStringJsonUpdateOwnerSchema,
    body: updateOwnerBody,
    response: {
      200: updateOwnerResponse,
    },
  },
};
const queryStringJsonLoadOwnerByPageSchema = {
  type: "object",
  properties: {
    page: { type: "integer", minimum: 1 },
    sortBy: { type: "string" },
    typeSort: { type: "string" },
  },
  required: ["page"],
};
const loadOwnerByPageResponse = {
  type: "object",
  properties: {
    owners: {
      type: "array",
      maxItems: 10,
      items: {
        type: "object",
        properties: {
          _id: idSchema,
          name: { type: "string" },
          description: { type: "string" },
          haveDelivery: { type: "boolean", nullable: true },
          minimumTimeForReSchedule: { type: "integer" },
          days1: {
            type: "object",
            required: [
              "monday1",
              "sunday1",
              "thursday1",
              "wednesday1",
              "tuesday1",
              "friday1",
              "saturday1",
            ],
            properties: {
              monday1: { type: "boolean" },
              sunday1: { type: "boolean" },
              thursday1: { type: "boolean" },
              wednesday1: { type: "boolean" },
              tuesday1: { type: "boolean" },
              friday1: { type: "boolean" },
              saturday1: { type: "boolean" },
            },
          },
          hourStart1: { type: "string" },
          hourEnd1: { type: "string" },
          days2: {
            type: "object",
            nullable: true,
            required: [
              "monday2",
              "sunday2",
              "thursday2",
              "wednesday2",
              "tuesday2",
              "friday2",
              "saturday2",
            ],
            properties: {
              monday2: { type: "boolean", nullable: true },
              sunday2: { type: "boolean", nullable: true },
              thursday2: { type: "boolean", nullable: true },
              wednesday2: { type: "boolean", nullable: true },
              tuesday2: { type: "boolean", nullable: true },
              friday2: { type: "boolean", nullable: true },
              saturday2: { type: "boolean", nullable: true },
            },
          },
          hourStart2: { type: "string", nullable: true },
          hourEnd2: { type: "string", nullable: true },
          days3: {
            type: "object",
            nullable: true,
            required: [
              "monday3",
              "sunday3",
              "thursday3",
              "wednesday3",
              "tuesday3",
              "friday3",
              "saturday3",
            ],
            properties: {
              monday3: { type: "boolean", nullable: true },
              sunday3: { type: "boolean", nullable: true },
              thursday3: { type: "boolean", nullable: true },
              wednesday3: { type: "boolean", nullable: true },
              tuesday3: { type: "boolean", nullable: true },
              friday3: { type: "boolean", nullable: true },
              saturday3: { type: "boolean", nullable: true },
            },
          },
          hourStart3: { type: "string", nullable: true },
          hourEnd3: { type: "string", nullable: true },
          hourLunchStart1: { type: "string", nullable: true },
          hourLunchEnd1: { type: "string", nullable: true },
          hourLunchStart2: { type: "string", nullable: true },
          hourLunchEnd2: { type: "string", nullable: true },
          hourLunchStart3: { type: "string", nullable: true },
          hourLunchEnd3: { type: "string", nullable: true },
          active: { type: "boolean", nullable: true },
          createdById: { type: "string" },
          createdAt: { type: "string" },
        },
      },
    },
    total: { type: "integer" },
  },
};
export const loadOwnerByPageGetSchema = {
  schema: {
    headers: headersJsonSchema,
    security: [{ bearerAuth: [] }],
    querystring: queryStringJsonLoadOwnerByPageSchema,
    response: {
      200: loadOwnerByPageResponse,
    },
  },
};
