export const env = {
  mongoUri: process.env.MONGO_URL_PROD ?? "mongodb://127.0.0.1:56328",
  jwtSecret: process.env.JWT_SECRET ?? "secret",
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET ?? "secret",
  port: process.env.PORT ?? 8080,
  environment: process.env.NODE_ENV ?? "development",
  redisPort: process.env.REDIS_PORT ?? 40043,
  redisUrl: process.env.REDIS_URL ?? "us1-active-example-40043.upstash.io",
  redisPassword: process.env.REDIS_PASSWORD ?? "YOUR_PASSWORD",
  googleMapsKey: process.env.GOOGLE_MAPS_API_KEY ?? "YOUR_GOOGLE_MAPS_KEY",
  kafkaUsername: process.env.KAFKA_USERNAME ?? "YOUR_KAFKA_USERNAME",
  kafkaPassword: process.env.KAFKA_PASSWORD ?? "YOUR_KAFKA_PASSWORD",
  kafkaHost: process.env.KAFKA_HOST ?? "YOUR_KAFKA_HOST",
  kafkaClientId: process.env.KAFKA_CLIENT_ID ?? "YOUR_KAFKA_CLIENT_ID",
  pagarmeKey: process.env.PAGARME_KEY ?? "YOUR_PAYMENT",
  wooviKey: process.env.WOOVI_KEY ?? "YOUR_PAYMENT",
  stripeKey: process.env.PUBLIC_STRIPE_KEY ?? "YOUR_PAYMENT",
  stripeKeySecret: process.env.SECRET_STRIPE_KEY ?? "YOUR_PAYMENT",
};
