@apiurl = http://127.0.0.1:3333/api

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0NDAwN2Q4ZS1hZjdmLTRiZDMtOTZmOC04NGJmM2ZlNTg2ZGUiLCJpYXQiOjE3MjkxNzM5NjgsImV4cCI6MTczNDM1Nzk2OH0.3f1AZq82PGtwm3lJWZMhh6nxSnv-Z6B3rIYm8shjHf8
@entityId=2d911a20-305b-4c00-b14d-b3be3ec5f8f0
@tweetresponsta=1fc7061f-dc6c-41ad-8b22-b359d5912e07
@tweetresponsta2=aabe26aa-fd10-4b5c-994b-e26505956e5b
@entityType=tweet

### POST add
POST {{apiurl}}/{{entityType}}/add  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userSlug": "devdoido2",
  "body": "RESPOSTA 2",
  "tweetId":"2d911a20-305b-4c00-b14d-b3be3ec5f8f0",
  "image":"ssdsd"
}

### GET loadById
GET {{apiurl}}/{{entityType}}/load?_id={{tweetresponsta}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET loadByPage
GET {{apiurl}}/{{entityType}}/loadByPage?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### PATCH update
PATCH {{apiurl}}/{{entityType}}/update?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userSlug": "devtop",
  "body": "Tweet massa2"
}

### DELETE delete
DELETE {{apiurl}}/{{entityType}}/delete?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

