@apiurl = http://127.0.0.1:3333/api

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI4ZTkzNmMzZC05MmI2LTQ5NGMtYjVmOS0yNzIxOTJlOWZhNjYiLCJpYXQiOjE3MTgzOTkxNTksImV4cCI6MTcyMzU4MzE1OX0.moKmWkHgkk7YPyAQM6HtcqWmdsG-fstLKm0We3GjYoU
@entityId=d5e7a601-5479-4ff3-9967-8b3ed9d86ea0

@entityType=photo

### POST add
POST {{apiurl}}/{{entityType}}/add  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://crazystack.571527a8590aad1eb25dc5b3338c4271.r2.cloudflarestorage.com/uploads/1718716228711-acompanhante.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=6da371cf59584f853aa90b34a71a1fca%2F20240618%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240618T131029Z&X-Amz-Expires=604800&X-Amz-Signature=6d659946b776126be34a15261634285a05c7fcef0aba7b96f937dd181c224124&X-Amz-SignedHeaders=host&x-id=GetObject",
  "key": "uploads/1718716228711-acompanhante.png",
  "provider": "cloudflare_r2",
  "expiresIn": "2024-06-25T13:10:29.761Z",
  "active": false,
  "expiresInSeconds": 604800
}

### GET loadById
GET {{apiurl}}/{{entityType}}/load?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET loadByPage
GET {{apiurl}}/{{entityType}}/loadByPage?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### DELETE delete
DELETE {{apiurl}}/{{entityType}}/delete?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

