@apiurl = http://127.0.0.1:3333/api
@token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI5YjM2ZWNjMS04ZTgwLTRmMGYtYTIxNy0yNWY2ZTAxNTgyYTAiLCJpYXQiOjE3MjkyNTA2NTYsImV4cCI6MTczNDQzNDY1Nn0.mK76MkkJ1t3YyDSVdBn90X31_ZrNdoAmZJb_Z6V7qUE
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI5YjM2ZWNjMS04ZTgwLTRmMGYtYTIxNy0yNWY2ZTAxNTgyYTAiLCJpYXQiOjE3MjkyNTY0MzgsImV4cCI6MTczNDQ0MDQzOH0.jET7V1decgU-TfCkrgNivRXiSCW0B32L8jkE-K01NKE
@entityId=399d1487-3396-450e-85e8-8232f1e7fb71

@entityType=follow

@userId=2f41abd8-9d68-48bf-b19b-675fe73563b9

### POST add
POST {{apiurl}}/{{entityType}}/add  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token2}}

{
  "userId": "2f41abd8-9d68-48bf-b19b-675fe73563b9"
}

### GET loadById
GET {{apiurl}}/{{entityType}}/load?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET loadByPage
GET {{apiurl}}/{{entityType}}/loadByPage?page=1&userId={{userId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### PATCH update
PATCH {{apiurl}}/{{entityType}}/update?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user1Slug": "devlouco"
}

### DELETE delete
DELETE {{apiurl}}/{{entityType}}/delete?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

