### Variables
@apiurl = http://127.0.0.1:3333/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI3MmI1OWNiYS1mOTk3LTRkMGItODcxYy0zNmZhZGZkNzkwZTIiLCJpYXQiOjE3MTY1NzM2NjQsImV4cCI6MTcyMTc1NzY2NH0.pBAY6QhssN_KUd0qFFKh8h-GbHpS0ZJZ2vUCUokJt60
@entityId=72b59cba-f997-4d0b-871c-36fadfd790e2

@myOwnerId=72b59cba-f997-4d0b-871c-36fadfd790e2

@ownerId=9b444370-6851-47bc-8235-952f8dfc19bc

@professionalId=f0bcc675-728e-4705-8ad2-50828dd0dc7f

### POST signup
POST {{apiurl}}/auth/signup HTTP/1.1
Content-Type: application/json

{
	"email": "gustavodevdoido@gmail.com",
	"password": "123456",
	"passwordConfirmation": "123456",
	"name": "devdoido",
	"phone": "34998355144",
	"role": "owner",
  "cpf":"403.815.550-69",
	"coord": {
		"lat": 0,
		"lng": 0
	}
}

### POST login
POST {{apiurl}}/auth/login HTTP/1.1
Content-Type: application/json

{
	"email": "gustavodevdoido@gmail.com",
	"password": "123456",
	"passwordConfirmation": "123456"
}

### DELETE delete user
DELETE {{apiurl}}/user/delete?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET loadUserById
GET {{apiurl}}/user/load?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### GET loadUserByPage
GET {{apiurl}}/user/loadByPage?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### POST add user
POST {{apiurl}}/user/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"email": "profissionaldevdoido@gmail.com",
  "name": "Profissional devdoido",
  "role":"professional",
  "myOwnerId":"72b59cba-f997-4d0b-871c-36fadfd790e2",
  "ownerId":"9b444370-6851-47bc-8235-952f8dfc19bc",
  "serviceIds":["4cbf792d-b92a-464c-8271-1cc5320b1235"],
	"password": "123456",
	"passwordConfirmation": "123456"
}

### PATCH update user
PATCH {{apiurl}}/user/update?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "teste 123",
  "serviceIds":["af1a4fb4-30fc-4032-bb86-47ccdda9a066"],
	"password": "12345672"
}

### GET loadByGeoNear
GET {{apiurl}}/user/loadByGeoNear?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


