@apiurl = http://127.0.0.1:3333/api

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJkNDljYmMwZS1mODg2LTRiOWEtYjg2Yi05MWMwZDYzMmNlN2EiLCJpYXQiOjE3MTcwODI2NjIsImV4cCI6MTcyMjI2NjY2Mn0.cCpe_-0_4RAtK7QNnNcTzXx_SPSZNWAc6mNvxXmZyzQ

@entityId=d49cbc0e-f886-4b9a-b86b-91c0d632ce7a

@myOwnerId=d49cbc0e-f886-4b9a-b86b-91c0d632ce7a

@ownerId=df1d757f-7d27-4956-8cdf-9a1c904e9dff

@professionalId=a487e135-9a20-456b-a310-6d23a5304a79

@entityType=user
### GET loadUserById
GET {{apiurl}}/{{entityType}}/load?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET loadUserByPage
GET {{apiurl}}/{{entityType}}/loadByPage?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### PATCH update
PATCH {{apiurl}}/{{entityType}}/update?_id={{entityId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe3",
  "active":false,
  "createdById": null
}

### DELETE delete user
DELETE {{apiurl}}/{{entityType}}/delete?_id={{entityId}}	 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### POST add
POST {{apiurl}}/{{entityType}}/add  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe2",
  "password": "123456",
  "passwordConfirmation": "123456",
  "cpf": "12345678900",
  "role": "professional",
  "myOwnerId":"d49cbc0e-f886-4b9a-b86b-91c0d632ce7a",
  "ownerId":"df1d757f-7d27-4956-8cdf-9a1c904e9dff",
  "serviceIds": ["79fe5bd5-841d-48ff-92a8-af79c2a1c7da"],
  "email":"email3@teste.com"
}


### POST signup
POST {{apiurl}}/auth/signup HTTP/1.1
Content-Type: application/json


{
  "email": "johndoe@gmail.com",
  "password": "123456",
  "passwordConfirmation": "123456",
  "name": "John Doe",
  "cpf": "12345678900",
  "phone": "12345678900",
  "role": "owner",
  "coord": {
    "lat": 0,
    "long": 0
  }
}

### POST LOGIN
POST {{apiurl}}/auth/login HTTP/1.1
Content-Type: application/json


{
  "email": "johndoe@gmail.com",
  "password": "123456",
  "passwordConfirmation": "123456"
}
